spring:
  thymeleaf:
    ## thymeleaf的配置 解决缓存的问题
    cache: false
    ## thymeleaf的配置 解决严格的页面校验的问题
    mode: LEGACYHTML5
  ## 数据源的配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: f088df87e10c40fe804c54e88d54b8e4
    #password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.15.188.249:3306/test?characterEncoding=utf8&allowMultiQueries=true
    #url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&allowMultiQueries=true

mybatis-plus:
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.allinjava.excel2sql.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
